CC=g++

all:
	$(CC) createkn01.cpp -o createkn01
	$(CC) bruteforce.cpp -o bruteforce
	$(CC) backtrack.cpp -o backtrack
	$(CC) dynpro.cpp -o dynpro

clean:
	rm createkn01
	rm bruteforce
	rm dynpro
	rm backtrack
